apiVersion: v1
kind: ConfigMap
metadata:
  name: auralux-config
  namespace: auralux
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-master.auralux.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless.auralux.svc.cluster.local:9092"
  MONGO_URI: "mongodb://mongodb-0.mongodb-headless.auralux.svc.cluster.local:27017"
  CORS_ORIGIN: "https://auralux.io"
  # Service discovery
  AUTH_SERVICE_URL: "http://auth-service.auralux.svc.cluster.local:3001"
  USER_SERVICE_URL: "http://user-service.auralux.svc.cluster.local:3002"
  MUSIC_SERVICE_URL: "http://music-service.auralux.svc.cluster.local:3003"
  STREAMING_SERVICE_URL: "http://streaming-service.auralux.svc.cluster.local:3004"
  PLAYLIST_SERVICE_URL: "http://playlist-service.auralux.svc.cluster.local:3005"
  HISTORY_SERVICE_URL: "http://history-service.auralux.svc.cluster.local:3006"
  RECOMMENDATION_SERVICE_URL: "http://recommendation-service.auralux.svc.cluster.local:3007"
  ANALYTICS_SERVICE_URL: "http://analytics-service.auralux.svc.cluster.local:3008"
  NOTIFICATION_SERVICE_URL: "http://notification-service.auralux.svc.cluster.local:3009"
