apiVersion: v1
kind: Secret
metadata:
  name: auralux-secrets
  namespace: auralux
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  JWT_REFRESH_SECRET: "CHANGE_ME_IN_PRODUCTION_REFRESH"
  SMTP_USER: ""
  SMTP_PASS: ""
  STREAM_SIGNING_SECRET: "CHANGE_ME_STREAM_SECRET"
